services:
  # The Database Service
  db:
    image: postgres:15
    container_name: property_automation_db  
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # --- 2. Backend Service (NEW) ---
  backend:
    build:
      context: .              # Important: Context is root so it can find requirements.txt
      dockerfile: app/Dockerfile
    container_name: property_backend
    restart: always
    ports:
      - "9999:8000"           # Expose API to your host machine
    volumes:
      - ./app:/app/app        # Hot-reload: Syncs your local code to the container
    env_file:
      - .env
    environment:
      # Pass .env vars
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - PROPERTY_RADAR_API_TOKEN=${PROPERTY_RADAR_API_TOKEN}
      # CRITICAL: Overwrite the host to use the docker service name
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
    
    dns:
      - 8.8.8.8
      - 8.8.4.4

  # Optional: GUI Viewer (http://localhost:8080)
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  # Add this under your 'db' service
  frontend:
    build: ./frontend
    container_name: property_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true

volumes:
  postgres_data: